language: node_js
node_js:
  - "10"
sudo: required
services:
  - docker
before_install:
  - npx vuepress build docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/.vuepress/dist
  on:
    branch: gh-pages
script:
  - bash test.sh
