language: node_js
node_js:
  - "10"
sudo: required
services:
  - docker
before_install:
  - |
      if [[ $TRAVIS_BRANCH == 'master' ]]; then
        npx vuepress build docs
      fi
      while IFS=, read -r col1 col2; do
          docker pull ${col2}
      done < services.csv

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/.vuepress/dist
  target-branch: gh-pages
  on:
    branch: master
script:
  - bash build.sh
  - bash test.sh
