language: node_js
sudo: required
services:
  - docker
before_install:
  - npx vuepress build docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: docs/.vuepress/dist
  on:
    branch: gh-pages
script:
  - bash test.sh
