language: node_js
node_js:
  - "10"
sudo: required
services:
  - docker
before_install:
  - |
      if [[ $TRAVIS_BRANCH == 'master' ]]; then
        npx vuepress build docs
      fi
      SERVICES=("fconvert" "foptimize" "futils")
      for a in ${SERVICES[@]}; do
        cd "$a"
        for b in */ ; do
          docker pull "$a/${b%?}"
        done
        cd ..
      done

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/.vuepress/dist
  target-branch: gh-pages
  on:
    branch: master
script:
  - bash build.sh
  - bash test.sh
