language: node_js
node_js:
  - "10"
cache:
  directories:
  - /home/travis/.nvm/versions/node/v10.9.0/bin/
  - /home/travis/.nvm/versions/node/v10.9.0/lib/node_modules/
sudo: required
services:
  - docker
before_install:
  - sudo apt-get install -y realpath
  - if [ ! -f "/home/travis/.nvm/versions/node/v10.9.0/bin/vuepress" ];then npm i -g vuepress; fi
  - if [ ! -f "/home/travis/.nvm/versions/node/v10.9.0/bin/gren" ];then npm i -g github-release-notes; fi
script:
  - bash build.sh
  - bash test.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/.vuepress/dist
  target-branch: gh-pages
  on:
    branch: master