language: node_js
node_js:
  - "10"
sudo: required
services:
  - docker
before_install:
  - docker pull futils/alpine
  - docker pull fconvert/image
  - docker pull fconvert/sound
  - docker pull fconvert/video
  - docker pull foptimize/gif
  - docker pull foptimize/png
  - docker pull foptimize/jpg
  - docker pull foptimize/svg
  - docker pull futils/resize
  - |
    if [[ $TRAVIS_BRANCH == 'master' ]]; then
      npx vuepress build docs
    fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/.vuepress/dist
  target-branch: gh-pages
  on:
    branch: master
script:
  - bash build.sh
  - bash test.sh
