language: node_js
node_js:
  - "10"
sudo: required
services:
  - docker
before_install:
  - bash build.sh travis
script:
  - bash build.sh
  - bash test.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/.vuepress/dist
  target-branch: gh-pages
  on:
    branch: master