#!/usr/bin/env bash

if [ ! -d ~/.fcli ]; then
  mkdir -p ~/.fcli
fi
if [ -e ~/.fcli/cli.sh ]; then
    rm -f ~/.fcli/cli.sh
fi
# Not very safe but oh wel... force cache also...
curl -s "https://raw.githubusercontent.com/jukefr/fyle/master/futils/cli/cli.sh?$((RANDOM%42424242))" > ~/.fcli/cli.sh

sh ~/.fcli/cli.sh "$@"
exit 0
